# Generated by Django 4.0.3 on 2022-03-30 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id_movimentacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('e', 'Entrada'), ('s', 'Saída')], max_length=1)),
                ('data', models.DateField()),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
