# Generated by Django 4.0.3 on 2022-11-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='categoria',
            field=models.CharField(choices=[('1', 'Casa'), ('2', 'Transporte'), ('3', 'Alimentação'), ('4', 'Saúde'), ('5', 'Vestuário'), ('6', 'Higiene'), ('7', 'Judicial')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
