# Generated by Django 4.0.3 on 2022-11-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Andamento'), ('2', 'Cancelada'), ('3', 'Concluída')], max_length=1)),
            ],
        ),
    ]
